apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  version: 0.1.0
  description: POS App

resources:
  - ns.yaml
  - service.yaml
  - deployment.yaml

images:
- name: ghcr.io/cse-labs/heartbeat
  newTag: 0.1.0
