---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: heartbeat
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/TX-Georgetown/heartbeat/overlays/v0.4.0
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
